# NUMPY FIRST CODE


* NumPy is a Python library that provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays. It is one of the fundamental packages for numerical computing in Python.

Some key features of NumPy include:

Multidimensional array object: NumPy provides a powerful ndarray object, which is a multi-dimensional array that can hold elements of the same type.                                   These arrays can be one-dimensional, two-dimensional, or multi-dimensional.

Array operations: NumPy provides a wide range of mathematical functions that operate on arrays element-wise, making it easy to perform numerical                          computations. These operations are implemented efficiently in compiled C code, making NumPy much faster than Python lists for                           numerical computations.

Broadcasting: NumPy allows for arithmetic operations between arrays of different shapes and sizes through a mechanism called broadcasting. This                       simplifies the writing of code and eliminates the need for explicit loops over array elements.

Linear algebra operations: NumPy provides functions for linear algebra operations such as matrix multiplication, matrix inversion, eigenvalue                                      decomposition, singular value decomposition, and more.

Random number generation: NumPy includes a submodule numpy.random for generating random numbers with various probability distributions.
                          Integration with other libraries: NumPy is the foundation for many other Python libraries used in scientific computing and                              data analysis, such as SciPy, pandas, matplotlib, and scikit-learn. 

In [1]:
import numpy as np

In [2]:
Myarr = np.array([0,1,2,3,4,5,6,7],np.int8) #This is one dimensional array and (np.int8) means 
                                            #hammare array ke ander 8 bit ki values he aaynge dont take too big values.

In [3]:
Myarr

array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int8)

In [4]:
print(Myarr)

[0 1 2 3 4 5 6 7]


In [5]:
Myarr2 = np.array([[0,1,2,3,4,5],[00,11,22,33,44,55]],np.int16) #This is creation of 2 dimentional array
                                                                #where []The number of list is numer of rows
                                                                #and the values are number of columns.

In [6]:
Myarr2[0,1]

1

In [7]:
Myarr2[1,0]

0

In [8]:
Myarr2[1,1]

11

In [9]:
Myarr2.dtype #Using the dtype you can get the date type of your array that you have created

dtype('int16')

In [10]:
Myarr2[1,0] = 88 #Like this we can update the value of our array in numpy

In [11]:
Myarr2

array([[ 0,  1,  2,  3,  4,  5],
       [88, 11, 22, 33, 44, 55]], dtype=int16)

In [12]:
Myarr2.shape #This will give the shape of our array row and column wise

(2, 6)

In [13]:
Myarr2.size #This is will give the length or number of elements present in array

12

# Array creation: 1) Conversion from other python structures

In [14]:
listarray = np.array([[0,1,2,3], [10,11,12,13],[20,21,22,23]])

In [15]:
listarray

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [16]:
listarray.dtype

dtype('int32')

In [17]:
listarray.size

12

In [18]:
listarray.shape

(3, 4)

In [19]:
np.array({1,2,3}) #creating dtype = object array are not efficient in numpy python

array({1, 2, 3}, dtype=object)

# 2) Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

In [20]:
zeros = np.zeros((2,3)) #This will create (2,3) shape 2D array in which all the values are 0. in float

In [21]:

zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
zeros.size

6

In [23]:
arang = np.arange(15) #This will create a 1D array from 0 to 14(arange value -1)

In [24]:
arang

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
lnspace = np.linspace(1,5,8) # This will create an numpy 1D array respectively(first number of array, last number of array, number of elements in array)
                             # i.e (1,5,8) and the space between all the elements are equal with data type float.


In [26]:
lnspace

array([1.        , 1.57142857, 2.14285714, 2.71428571, 3.28571429,
       3.85714286, 4.42857143, 5.        ])

In [27]:
empty = np.empty((2,6)) #This will create empty numpy array shape of (2,6) and the values are all rendom inside the array.

In [28]:
empty

array([[1.01055453e-311, 2.81617418e-322, 0.00000000e+000,
        0.00000000e+000, 1.11260619e-306, 1.61590357e+184],
       [4.71080907e-090, 4.27629914e-033, 6.54774225e-043,
        1.36967060e-071, 6.48224660e+170, 4.93432906e+257]])

In [29]:
empty_like = np.empty_like(arang) #This will create an empty array same as "arang" array which we have created before and the values are random.

In [30]:
empty_like

array([3801155, 5570652, 6619251, 7536754, 4259932, 6881380, 7929972,
       6029409, 7340097, 4456560, 7602273, 6029409, 7274572, 6357091,
       6029420])

In [31]:
identity = np.identity(37)#This will create (37,37) shape identity matrix for us

In [32]:
identity

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [33]:
arr = np.arange(99) #We have created an array from (0 to 98) 1D numpy array.

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [35]:
arr = arr.reshape(3,33) #This method reshape the 1D array into desirable shape(2D or 3D) array
                  #but the limit is the array size or all the elements in array should meet the shape of array which you wnat to create
                  #Exampele -> here the elements are 99 so we can make (3x33) shape array because (3x33 = 99)

In [36]:
arr #here arr is changed because we update the arr using the reshape function

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [37]:
arr.shape #Here the shape changes

(3, 33)

In [38]:
arr = arr.ravel()

In [39]:
arr #here the arr become again the orignal before reshaped() array which we created using the ravel() method.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [40]:
arr.shape #Now we retain the orignal shape of the arr numpy array.

(99,)

# NUMPY AXIS

* check notes in microsoft notebook

In [41]:
lis = [[1,2,3], [4,5,6], [7,1,0]]

In [42]:
ar = np.array(lis)

In [43]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [44]:
ar.sum(axis = 0) #so, axis 0 represent or extends the rows and we are adding the so ,
                 #we are doing the sum of the value  like (1+4+7) = 12 so on...

array([12,  8,  9])

In [45]:
ar.sum(axis = 1) #axis 1 represent the columns and we are doint the sum i.e -> 1+2+3 = 6 so.. continue ...

array([ 6, 15,  8])

# Attributes of numpy

In [46]:
ar.T #This will do the transpose of our matrix i.e rows into columns and vise-versa

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [47]:
ar.flat #This will provide us a iterator which we can used in for loop to acess the elements of the matrix.

In [48]:
for items in ar.flat: #Using for loop with the help of flat attribute.
    print(items)

1
2
3
4
5
6
7
1
0


In [49]:
ar.ndim #ndim will give us that number of dimension of our array.

2

In [50]:
ar.size #prints the n umber of elements in our matrix

9

In [51]:
ar.nbytes #nbytes will tell that how much bytes is taken by our elements.

36

In [52]:
one = np.array([1,2,3,3737,5,7])

In [53]:
one.argmin() #This will give the index number which will contain the minimum value .

0

In [54]:
one.argmax() #This will give the index number which will contain the maximum value.

3

In [55]:
one.argsort() #This function will give the order of index number of our array such that our array will get sort in Accending order.

array([0, 1, 2, 4, 5, 3], dtype=int64)

* Now lets check the same methods for the 2D array

In [56]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [57]:
ar.argmin() #This method will convert our 2D array as 1D array and then print the index number which has the minimum value

8

In [58]:
ar.argmax() #Same as argmin() method but it will print the index number which contain the maximum value.

6

In [60]:
ar.argmin(axis = 0) #Now here It will check the row wise and then give the index numbers which contain minimum value.

array([0, 2, 2], dtype=int64)

In [61]:
ar.argmax(axis = 1) #Now here it will check the column wise and then give the index numbers which contain maximum value.

array([2, 2, 0], dtype=int64)

In [62]:
ar.argsort() #check output by yourself

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [63]:
ar.argsort(axis = 0) 

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [64]:
ar.argsort(axis = 1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [92]:
ar.tolist() #This will return the numpy array to python list

[[1, 2, 3], [4, 5, 6], [7, 1, 0]]

# Mathemetical Operation provide by numpy to perform on numpy array

In [65]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [66]:
ar2 = np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [67]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [68]:
ar + ar2 #Additon of matrix

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [69]:
ar - ar2 #Subtraction of matrix

array([[ 0,  0,  2],
       [ 0,  5,  0],
       [-1,  0,  0]])

In [70]:
ar * ar2 #Multiplication of matrix

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [71]:
np.sqrt(ar) #This will give the square root of the array.

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [72]:
ar2.sum() #will give the sum of all the values present in numpy array.

23

In [73]:
ar2.min() #give the minumum value of a matrix.

0

In [74]:
ar2.max()#give the maximum value of a matrix.

8

In [75]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [81]:
np.where(ar2>5) #This will return the touple of array as output
               #This will find the element for me in 'ar' array which are greater then 5.

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [82]:
np.where(ar2<=1)

(array([0, 0, 1, 2, 2], dtype=int64), array([0, 2, 1, 1, 2], dtype=int64))

In [83]:
type(np.where(ar<=1)) #see the type is tuple.

tuple

In [84]:
np.count_nonzero(ar2) #This will give the count or number of elements that are non zero.

7

In [85]:
np.nonzero(ar2) #This will give the tuple for every dimension of an array.ex->[0,0] will have a non zero value.

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 2, 0, 1], dtype=int64))

* Now lets compare the list size of python and numpy array

In [86]:
import sys

In [87]:
python_arr = [0,4,55,2]

In [89]:
numpy_arr = np.array(python_arr)

In [90]:
sys.getsizeof(1)*len(python_arr) #This will print the size ocupies by all the elements of python array(list)

112

In [91]:
numpy_arr.itemsize * numpy_arr.size #This will print the size ocupies by all the elements of numpy array

16

# https://docs.scipy.org/doc/numpy-1.6.0/reference/generated/numpy.ndarray.html  
# TAKE REFERENCE FROM THE LINK ORIGNAL DOCUMENTATION.